#                               Assignment 3 24100003 

# Problem 1

We know that $A v_i=\lambda_i v_i$
We can also write this as:
\begin{equation}
AV=\Lambda V
\end{equation}
Where $V$ is the matrix of eigenvectors of  A stacked in order of decreasing eigenvalues and, $\Lambda$ is the diagonal matrix of eigenvalues of A.
\begin{equation}
V^{-1}AV=\Lambda
\end{equation}
We can take the determinant on both of the sides.
\begin{equation}
|V^{-1}AV|=|\Lambda|\\
|V^{-1}| \times |V| \times |A| = |\Lambda|
\end{equation}
We know that $|V^{-1}|=\frac{1}{|V|}$ and that the determinant of a diagonal matrix is just the product of its diagonal enteries.
\begin{equation}
|A|=\Pi_{j=0}^n \Lambda_{jj}\\
|A|=\Pi_{j=0}^n \lambda_{j}
\end{equation}

# Problem 2

Let's take 2 upper triangular square matirces $A,B$ of dimensions $n\times n$:
\begin{align}
\begin{pmatrix}
A_{00} && A_{01} && A_{02} &&\cdots &&A_{0n} \\
0 && A_{11} && A_{12}&& \cdots &&A_{1n} \\
\vdots && 0 && A_{22} && \cdots && A_{2n}\\
\vdots  && \vdots && \vdots&& \ddots&&\vdots \\
0 && 0 && 0&&0&& A_{nn}
\end{pmatrix}
\begin{pmatrix}
B_{00} && B_{01} && B_{02} &&\cdots &&B_{0n} \\
0 && B_{11} && B_{12}&& \cdots &&B_{1n} \\
\vdots && 0 && B_{22} && \cdots && B_{2n}\\
\vdots  && \vdots && \vdots&& \ddots &&\vdots \\
0 && 0 && 0&&0&& B_{nn}
\end{pmatrix}
\end{align}



Lets' write the matrix multiplication in terms of components:
\begin{align}
C=A \times B \\
C_{ij}=\sum_{k=0}^{k=n}A_{ik}B_{kj}
\end{align}

if we choose an i, we have the constraint that all $A_{ik}=0$ if $k<i$ and for j , all $B_{kj}=0$ if $k>j$,since the matrices are upper triangular.

Which makes the equation above, rest of the products are just zero :
\begin{align}
C_{ij}=\sum_{k=i}^{k=j}A_{ik}B_{kj}
\end{align}

Let's apply the criteria for upper triangular matrix. let's choose an $i$ and see if for all $j<i$ ,$C_{ij}=0$
We can see that if we take $j<i$ our summation becomes invalid in which case its zero, hence it is an upper triangular matrix.

Similarly if we fix a j and take $i>j$ our summation again becomes invalid for which the sum was zero.

Hence, the matrix C is and upper triangular matrix.

part b)

let's take two orthogonal matrices $A$ and $B$.

\begin{align}
C=A B \\
C^{-1}=B^{-1}A^{-1}\\
C^{-1} = B^{T}A^{T} =C^{T}
\end{align}

# Problem 3

Let's take perturbed problem:
\begin{align}
A(x+\Delta x)=b+\Delta b\\
A\Delta x =\Delta b \\
\Delta x = A^{-1} \Delta b\\
\end{align}
let's take the norm on each side:
\begin{align}
||\Delta x||=||A^{-1} \Delta b||
\end{align}
and now lets divide each side with $||x||$
\begin{align}
\frac{||\Delta x||}{||x||}=\frac{||A^{-1} \Delta b||}{||A^{-1} b||}\\
\frac{||\Delta x||}{||x||} \leq \frac{||A^{-1} || \times||\Delta b||}{||A^{-1} b||}\\
\kappa=\frac{||A^{-1}||}{||A^{-1} b||}
\end{align}


# Problem 4  


LU Decomposition

In [1]:
import numpy as np
from numpy import linalg as la
def ludec(mat_t):
    new_T=np.copy(mat_t)
    UT=new_T.copy()
    LT=np.identity(new_T.shape[0])
    for j in range(new_T.shape[0]-1):
        coefficient=0
        for i in range(j+1,new_T.shape[0]):
            coefficient=UT[i][j]/UT[j][j]
            UT[i]-=coefficient*UT[j]
            LT[i][j]=coefficient
    return [UT,LT]
matrix=np.array(([1.,2.,3.,4.],[15.,14.,13.,12.],[9.,6.,5.,4.],[9.,4.,5.,.2]))
print(ludec(matrix))
ludec(matrix)[1]@ludec(matrix)[0]

[array([[  1. ,   2. ,   3. ,   4. ],
       [  0. , -16. , -32. , -48. ],
       [  0. ,   0. ,   2. ,   4. ],
       [  0. ,   0. ,   0. ,  -5.8]]), array([[ 1.   ,  0.   ,  0.   ,  0.   ],
       [15.   ,  1.   ,  0.   ,  0.   ],
       [ 9.   ,  0.75 ,  1.   ,  0.   ],
       [ 9.   ,  0.875,  3.   ,  1.   ]])]


array([[ 1. ,  2. ,  3. ,  4. ],
       [15. , 14. , 13. , 12. ],
       [ 9. ,  6. ,  5. ,  4. ],
       [ 9. ,  4. ,  5. ,  0.2]])

Euclidean Norm

In [2]:
def euclid(T):
    norm =0
    for rows in T:
        for elements in rows:
            norm+=elements**2
    return np.sqrt(norm)
print(euclid(matrix))

32.31160782133876


infinity norm

In [3]:
def inftnorm(T):
    rowsum=[]
    for rows in T:
        summ=0
        for elements in rows:
            summ+=np.abs(elements)
        rowsum.append(summ)
    return max(rowsum)
inftnorm(matrix)

54.0

# Problem 5

Let's take that the left and right eigenvectors give different eigenvalues:
\begin{align}
Ax_i=\lambda_i x_i\\
y_i^TA=\mu_i y^T_i
\end{align}
We can say that $\mu_i$ are the eigenvalues of the transopose matrix.
\begin{gather}
det(A-\lambda I)=det(A^T-\mu I)\\
det(A-\lambda I)=det(A^T-\mu I^T)\\
det(A-\lambda I) = det(A-\mu I)^T\\
\lambda=\mu
\end{gather}


# Problem 6

For a matrix that is sensitive to perturbations in a linear system of equations has a large condition number i.e:
\begin{align}
\kappa=||A||||A^{-1}||
\end{align}
For it to have sensitive eigenvalues, the eigenvalue condition number requires their left and right eigenvectors to be close to orthogonal:
\begin{align}
\kappa^{\lambda_i}=\frac{1}{|u_i^Tv_I|}
\end{align}

for the eigenvectors to be senstive, you need atleast  2 eigenvalues to be close or the left and right eigenvectors to be orthogonal.

The matrix can not be symmetric, it is preferrable that the norm of its inverse is not very small. let's make an upper triangular matrix that has close eigenvalues.

In [4]:
matrix_A = np.array([[1,2,5],[0,1.50001,9],[0,0,1.1]])
la.norm(matrix_A)*la.norm(la.inv(matrix_A))

92.21624909128354

In [5]:
la.eig(matrix_A)

(array([1.     , 1.50001, 1.1    ]),
 array([[ 1.        ,  0.97014136, -0.99841859],
        [ 0.        ,  0.24254019, -0.05616122],
        [ 0.        ,  0.        ,  0.00249612]]))

In [6]:
la.eig(np.transpose(matrix_A))

(array([1.1    , 1.50001, 1.     ]),
 array([[ 0.        ,  0.        ,  0.0032256 ],
        [ 0.        ,  0.04440172, -0.01290213],
        [ 1.        ,  0.99901376,  0.99991156]]))

We can see that eigenvectors corresponding to eigenvalue = 1.01 are close to orthogonal , the condition number is also high and hence the matrix :
\begin{equation}
\begin{pmatrix}
1 && 2 && 5 \\
0 && 1.5 && 9 \\
0 && 0 && 1.1
\end{pmatrix}
\end{equation}
is highly sensitive to all three cases.

# Problem 7

We know that $AA^{-1}=I$
We can break the problem into the matrix A, being multiplied with a column vector $v_i$ such that it gives the coordinate basis vector $e_i$. All such vectors stacked together will form the inverse matrix.
\begin{equation}
Av_i=e_i\\
L(Uv_I)=e_i\\
Ly=e_i\\
Uv_i=e_i
\end{equation}
We can find y using forward substitution, and then using backward substitutions, the inverse matrix.

In [45]:
def ludec(mat_t):
    new_T=np.copy(mat_t)
    UT=new_T.copy()
    LT=np.identity(new_T.shape[0])
    for j in range(new_T.shape[0]-1):
        coefficient=0
        for i in range(j+1,new_T.shape[0]):
            coefficient=UT[i][j]/UT[j][j]
            UT[i]-=coefficient*UT[j]
            LT[i][j]=coefficient
    return [UT,LT]
def LTsol(Mat_T,b):
    x=np.zeros(len(b))
    for i in range (len(b)):
        par_sum_x=0
        for j in range (i):
            par_sum_x+=Mat_T[i][j]*x[j]
        x[i]=b[i]-par_sum_x
        x[i]/=Mat_T[i][i]
    return x
def UTsol (mat_T,b):
    x=np.zeros(len(b))
    for i in range (len(b)-1,-1,-1):
        par_sum_x=0
        for j in range(i+1,b.size):
            par_sum_x+=mat_T[i][j]*x[j]
        x[i]=(b[i]-par_sum_x)/mat_T[i][i]
    return x
def inv(mat_T):
    A=ludec(mat_T)
    I=np.identity(mat_T.shape[1])
    B=[]
    A_inv=[]
    for cols in I:
        B.append(LTsol(A[1],cols))
    for col in B:
        A_inv.append(UTsol(A[0],col))
    return np.array(A_inv).transpose()
print("      inverse through LU Decomposition\n",inv(matrix),"\n\n\n","         Inverse through np.linalg\n",la.inv(matrix))

      inverse through LU Decomposition
 [[ 2.50000000e-01 -2.50000000e-01  5.00000000e-01  1.11022302e-16]
 [-8.59913793e-01  4.50431034e-01 -4.82758621e-01 -1.72413793e-01]
 [ 2.19827586e-01  9.91379310e-02 -5.34482759e-01  3.44827586e-01]
 [ 4.52586207e-01 -2.37068966e-01  5.17241379e-01 -1.72413793e-01]] 


          Inverse through np.linalg
 [[ 2.50000000e-01 -2.50000000e-01  5.00000000e-01  6.66133815e-17]
 [-8.59913793e-01  4.50431034e-01 -4.82758621e-01 -1.72413793e-01]
 [ 2.19827586e-01  9.91379310e-02 -5.34482759e-01  3.44827586e-01]
 [ 4.52586207e-01 -2.37068966e-01  5.17241379e-01 -1.72413793e-01]]


[array([[  1. ,   2. ,   3. ,   4. ],
        [  0. , -16. , -32. , -48. ],
        [  0. ,   0. ,   2. ,   4. ],
        [  0. ,   0. ,   0. ,  -5.8]]),
 array([[ 1.   ,  0.   ,  0.   ,  0.   ],
        [15.   ,  1.   ,  0.   ,  0.   ],
        [ 9.   ,  0.75 ,  1.   ,  0.   ],
        [ 9.   ,  0.875,  3.   ,  1.   ]])]

Determinant:
\begin{equation}
A=LU\\
|A|=|LU|=|L||U|
\end{equation}
We know that the determinant of a triangular matrix is just the product of its diagonals, furthermore, the diagonals of the L matrix are all 1's so we only need to multiply the diagonals of U matrix.

In [8]:
def det(mat_T):
    A=np.diagonal(ludec(mat_T)[0])
    det=1
    for elements in A:
        det*=elements
    return det
mat=np.array([[1.,2.,3.],[3.,1.,6.],[7.,8.,9.]])
print("Determinant through LU decompositon\n   ",det(mat),"\n\n\n","\nDeterminant through np.linalg\n   ",la.det(mat))  

Determinant through LU decompositon
    42.0 


 
Determinant through np.linalg
    42.00000000000002


# Problem 8

Let's say that the Dolittle's LU decomposition is not Unique i.e:
\begin{equation}
A=LU=BT\\
\end{equation}
Here $B$ is the bottom(lower) and $T$ is the Top(upper) triangular matrix.
\begin{equation}
L=\begin{pmatrix} 1 && 0 && 0 && \cdots && 0 \\ L_{10} && 1 && 0&& \cdots && 0 \\ L_{20} && L_{21} &&1 &&\cdots&& 0 \\ \vdots &&\vdots&&\vdots &&\ddots &&\vdots \\L_{n0} && L_{n1}&&L_{n2}&&\cdots&&1 \end{pmatrix}  U = \begin{pmatrix}
U_{00} && U_{01} && U_{02} &&\cdots &&U_{0n} \\
0 && U_{11} && U_{12}&& \cdots &&U_{1n} \\
\vdots && 0 && U_{22} && \cdots && U_{2n}\\
\vdots  && \vdots && \vdots&& \ddots &&\vdots \\
0 && 0 && 0&&0&& U_{nn}
\end{pmatrix}
\end{equation}
\begin{equation}
A_{ij}=\sum_{k=0}^{k=n}L_{ik}U_{kj} =\sum_{k=0}^{k=n}B_{ik}T_{kj} 
\end{equation}


For the lower triangular matrix, if you fix an $i$, all of the $k>i$ the components will be zero.
Whereas, when you fix $j$ all of the elements $k>j$ will be zero.
\begin{equation}
A_{ij}=\sum_{k=0}^{k=min (i,j)}L_{ik}U_{kj} =\sum_{k=0}^{k= min(i,j)}B_{ik}T_{kj} \\
A_{0j}=\sum_{k=0}^{k=j}L_{0k}U_{kj} =\sum_{k=0}^{k= j}B_{0k}T_{kj} \\
L_{0j}=B_{0j}=\delta_{0j}\\
A_{0j}=U_{0j}=T_{0j}
\end{equation}
additionallly the first row of the $A$ matrix will be just $U_{00} =\times L_{i0}$
\begin{gather}
A_{i0}=U_{00}L_{i0}=U_{00}B_{i0}\\
L_{i0}=B_{i0}\\
\end{gather}
If we write the matrix multiplication in the component form, we will have:


We can see that factoring U and T requires:
\begin{equation}
U_{ij}=A_{ij}-\sum_{k=0}^{j-1}L_{ik}U_{kj}\\
L_{ij}=\frac{U_{ij}}{U_{jj}}\\
T_{ij}=A_{ij}-\sum_{k=0}^{j-1}B_{ik}T_{kj}\\
B_{ij}=\frac{T_{ij}}{T_{jj}}\\
\end{equation}

As we have shown the starting elements (rows and columns) are the same, the equations that will follow will include those elements in the same exact positons hence the $B=L$ and $U=T$

# Problem 9

In [48]:
def ludec(mat_t):
    new_T=np.copy(mat_t)
    UT=new_T.copy()
    LT=np.identity(new_T.shape[0])
    p=0
    for j in range(UT.shape[0]-1):
        k = np.argmax(np.abs(UT[j:,j])) + j
        if k != j:
            p=p+1
            UT[j,:], UT[k,:] = UT[k,:], UT[j,:].copy()
        coefficient=0
        for i in range(j+1,new_T.shape[0]):
            coefficient=UT[i][j]/UT[j][j]
            UT[i]-=coefficient*UT[j]
            LT[i][j]=coefficient
        A=np.diagonal(UT)
        det=(-1)**(p)
        for elements in A:
            det*=elements
    return [UT,LT,det]

In [49]:
ludec(matrix)

[array([[15.        , 14.        , 13.        , 12.        ],
        [ 0.        , -4.4       , -2.8       , -7.        ],
        [ 0.        ,  0.        ,  1.45454545,  1.5030303 ],
        [ 0.        ,  0.        ,  0.        ,  1.93333333]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ],
        [ 0.06666667,  1.        ,  0.        ,  0.        ],
        [ 0.6       ,  0.54545455,  1.        ,  0.        ],
        [ 0.6       , -0.24242424, -0.875     ,  1.        ]]),
 185.6000000000001]

In [42]:
la.det(np.array([[1.,2.],[3.,4.]]))

-2.0000000000000004

In [66]:
import numpy as np

def lu_pivot(A):
    n = A.shape[0]
    L = np.eye(n)
    U = np.copy(A)
    p = 0 # number of row interchanges
    for j in range(n-1):
        k = np.argmax(np.abs(U[j:,j])) + j
        if k != j:
            p=p+1
            U[[j,k],:] = U[[k,j],:]
            
        for i in range(j+1, n):
            coeff = U[i j]/U[j, j]
            U[i]= U[i]- coeff * U[j, j:]
            L[i, j] = coeff
    
    det = ((-1)**p)
    for i in range(n):
        det *= U[i,i]

    
    return L, U, det

B = np.array([[1, 2], [3, 4]])
L, U, det = lu_pivot(B)
print("U:")
print(U)
print("L:")
print(L)
print("det:",det)

U:
[[3.         4.        ]
 [0.         0.66666667]]
L:
[[1.         0.        ]
 [0.33333333 1.        ]]
det: -2.0
