In [2]:
from numpy import linalg as la
A=[[0.2161,0.1441],[1.2969,0.8648]]
B=[0.1440,0.8642]
la.solve(A,B)

array([ 2., -2.])

if we disturb one of the elements slightly. the solutions change drastically.

In [4]:
from numpy import linalg as la
A=[[2.,1.],[1.,2.]]
B=[2,7]
la.solve(A,B)

array([-1.,  4.])

If we have a large system of equations, we would like to know before hand if our solutions are senstive or not. The first guess is that it may be dependent on the determinant. Let's check in the case of sensitive solutions, what were the determinants like? Let's look at the determinant of a sensitive solutions

In [6]:
from numpy import linalg as la
A=[[0.2161,0.1441],[1.2969,0.8648]]
B=[0.1440,0.8642]
la.solve(A,B)
la.det(A)#The determinant is small in this case which makes us think that maybe we are correct in our guess

-9.999999998544968e-09

In [17]:
import numpy as np
A2=np.array([[0.2,0.101],[0.1,0.2]])
B2=np.array([0.2,0.7])
la.solve(A2,B2)
la.det(A2)# the determinant is small in this case but the solutions are stable.

0.029900000000000013

if we say that the solution becomes more sensitve than it is incorrect as if we divide the equations by 10 or 100 the senstivity of the solution remains the same hower the determinant goes down by a factor of $100$ or $10^3$

Euclidean Norm:
\begin{equation}
||A||=\sqrt{\Sigma_{i=0}^{n-1}\Sigma_{j=0}^{n-1}|A_{ij}^2|}
\end{equation}

Infinite Norm:
\begin{equation}
||A||_\infty = max_{0\leq i \leq n-1}[\Sigma|A_{ij}|]
\end{equation}
This is the largest sum of each row

What we want is that $||A||=||A^{-1}||$ to be small

\begin{equation}
||A||=0 \leftrightarrow  |A_{ij}|=0
\end{equation}

Hypothesis for non sensitive, $det(A)<<||A||$ 

In [21]:
print(la.norm(A))
print(la.det(A))

1.5802824652573981
-9.999999998544968e-09


In [59]:
upp_T=np.triu([-2,-2,-2,-2,-2,-2,-2,-2])
#i=np.zeros(64).reshape(8,8)
i=np.identity(8)
i[0][0]=-1
upp_T=upp_T+4*np.identity(8)
#print(upp_T)
b=np.array([1,-1]*4)
b=b.reshape(8,1)
print(upp_T,b)
la.solve(upp_T,b)


[[ 2. -2. -2. -2. -2. -2. -2. -2.]
 [ 0.  2. -2. -2. -2. -2. -2. -2.]
 [ 0.  0.  2. -2. -2. -2. -2. -2.]
 [ 0.  0.  0.  2. -2. -2. -2. -2.]
 [ 0.  0.  0.  0.  2. -2. -2. -2.]
 [ 0.  0.  0.  0.  0.  2. -2. -2.]
 [ 0.  0.  0.  0.  0.  0.  2. -2.]
 [ 0.  0.  0.  0.  0.  0.  0.  2.]] [[ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [-1]
 [ 1]
 [-1]]


array([[-21. ],
       [-11. ],
       [ -5. ],
       [ -3. ],
       [ -1. ],
       [ -1. ],
       [  0. ],
       [ -0.5]])

In [66]:
k=np.array([[4,3,2,1],[3,3,2,1],[0,2,2,1],[0,0,1,1]])
la.eig(k)

(array([7.31274213, 2.06663092, 0.13674761, 0.48387934]),
 array([[ 0.73319229, -0.50597951, -0.03552739,  0.08981592],
        [ 0.63293   , -0.26114648,  0.22427524, -0.09580043],
        [ 0.24559146,  0.599716  , -0.63638388, -0.45466534],
        [ 0.03890408,  0.56225259,  0.73719331,  0.88092838]]))

In [65]:
k=np.array([[4,3,2,1.01],[3,3,2,1],[0,2,2,1],[0,0,1,1]])
la.eig(k)

(array([7.3129755 , 2.06287308, 0.12477715, 0.49937427]),
 array([[ 0.73322121, -0.50489056, -0.04175813,  0.09211235],
        [ 0.63290497, -0.2628705 ,  0.23432976, -0.11006428],
        [ 0.24557035,  0.59881226, -0.63967137, -0.44302653],
        [ 0.0388993 ,  0.56339018,  0.73086686,  0.88494557]]))