In [1]:
from numpy import linalg as la
import numpy as np
A=np.array([[4,3,2,1],[3,3,2,1],[0,2,2,1],[0,0,1,1]])
A_perturbed = np.array([[4,3,2,1.01],[3,3,2,1],[0,2,2,1],[0,0,1,1]])
B=np.array([[4,4,0,0],[0,3,4,0],[0,0,2,4],[0,0,0,1]])
B_perturbed = np.array([[4,4,0,0],[0,3,4,0],[0,0,2,4],[0.005,0,0,1]])
print(la.eig(A))
print(la.eig(A_perturbed))
print(la.eig(B))
print(la.eig(B_perturbed))

(array([7.31274213, 2.06663092, 0.13674761, 0.48387934]), array([[ 0.73319229, -0.50597951, -0.03552739,  0.08981592],
       [ 0.63293   , -0.26114648,  0.22427524, -0.09580043],
       [ 0.24559146,  0.599716  , -0.63638388, -0.45466534],
       [ 0.03890408,  0.56225259,  0.73719331,  0.88092838]]))
(array([7.3129755 , 2.06287308, 0.12477715, 0.49937427]), array([[ 0.73322121, -0.50489056, -0.04175813,  0.09211235],
       [ 0.63290497, -0.2628705 ,  0.23432976, -0.11006428],
       [ 0.24557035,  0.59881226, -0.63967137, -0.44302653],
       [ 0.0388993 ,  0.56339018,  0.73086686,  0.88494557]]))
(array([4., 3., 2., 1.]), array([[ 1.        , -0.9701425 ,  0.88888889, -0.76429148],
       [ 0.        ,  0.24253563, -0.44444444,  0.57321861],
       [ 0.        ,  0.        ,  0.11111111, -0.28660931],
       [ 0.        ,  0.        ,  0.        ,  0.07165233]]))
(array([4.04884232, 0.95115768, 2.18205744, 2.81794256]), array([[ 0.99991899,  0.75725717, -0.90713923, -0.95891902],
 

In [3]:
condition_num_a=la.norm(A)*la.norm(la.inv(A))
condition_num_b=la.norm(B)*la.norm(la.inv(B))
print(condition_num_a)
print(condition_num_b)

126.74383614203887
40.129477943277564


\begin{equation}
AV = \lambda V \\
(A + \Delta A)(V_i + \Delta V_i)=(\lambda_i+\Delta\lambda_i)(V_i + \Delta V_i)\\
\end{equation}
