In [7]:
L=[11,7,19,22,25]
import numpy as np
xs=np.array(L)
print(xs,L)
print(xs.size)
print(xs.dtype)
print(np.array([1.]*4))

[11  7 19 22 25] [11, 7, 19, 22, 25]
5
int32
[1. 1. 1. 1.]


$x=y$

In [8]:
x= np.array(L,dtype=np.float64)
print(xs[1])
print(xs[1:3])
test=xs[1:3]
test[:]=0.0
print(xs)


7
[ 7 19]
[11  0  0 22 25]


In [12]:
def f(x):
    return x**2.0+2.*x
P=[1,2,3,4,5]
l=np.array(P)
print(f(l))

[ 3.  8. 15. 24. 35.]


Matrices

In [30]:
LL=[[1,2,3,4],[1,2,5,6],[19,20,32,4],[3,4,3,1]]
print(LL)
A=np.array(LL)

[[1, 2, 3, 4], [1, 2, 5, 6], [19, 20, 32, 4], [3, 4, 3, 1]]


In [26]:
print(A.size)
print(len(A))
print(A.ndim)
print(A.shape)

20
4
2
(4, 5)


In [52]:
k=np.identity(3)
A=np.arange(1,10).reshape(3,3)
B=np.arange(11,20).reshape(3,3)
#C=A@B
C=np.dot(A,B)
print(C)
print(np.trace(C))
from numpy import linalg as la
a=np.array([[1,1],[1,1.002]])
b=np.array([2,2.001])
print(la.solve(a,b))
c=np.array([0.9911,-0.4870])
v=b-a@c
print(v)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]
711
[1.5 0.5]
[1.4959   1.497874]


lab pe aati- Allama iqbal f.t. Travis Scott

In [53]:
k=np.array([[1,1],[1,1.002]])
l=np.array([2,2.001])
print(la.solve(k,l))

[1.5 0.5]
