In [1]:
import numpy as np
from numpy import linalg as la
mat_A=np.array(([8,0,0,0],[1,6,0,0],[5,6,4,0],[7,8,9,1]))
b=np.array([1,2,3,4])
la.norm(mat_A)*la.norm(la.inv(mat_A))
mat_A.shape[1]


4

In [2]:
def LTsol(Mat_T,b):
    x=np.zeros(len(b))
    for i in range (len(b)):
        par_sum_x=0
        for j in range (i):
            par_sum_x+=Mat_T[i][j]*x[j]
        x[i]=b[i]-par_sum_x
        x[i]/=Mat_T[i][i]
    return x
def UTsol (mat_T,b):
    x=np.zeros(len(b))
    for i in range (len(b)-1,-1,-1):
        par_sum_x=0
        for j in range(i+1,b.size):
            par_sum_x+=mat_T[i][j]*x[j]
        x[i]=(b[i]-par_sum_x)/mat_T[i][i]
    return x
mat_k=np.triu([4,3,2,1])
b=np.array([5,2,1,3])
print(UTsol(mat_k,b))
la.solve(mat_k,b)

[ 0.75        0.33333333 -1.          3.        ]


array([ 0.75      ,  0.33333333, -1.        ,  3.        ])

In [3]:
la.solve(mat_k,b)

array([ 0.75      ,  0.33333333, -1.        ,  3.        ])

In [4]:
def GaussianElimination(mat_T,b):
    new_T=mat_T.copy()
    bnew=np.copy(b)
    for j in range(len(b)-1):
        coefficient=0
        for i in range(j+1,len(b)):
            coefficient=new_T[i][j]/new_T[j][j]
            new_T[i]-=coefficient*new_T[j]
            bnew[i]-=coefficient*bnew[j]
    return [new_T,bnew]
mat=np.array(([1.,2.,3.,4.],[4.,5.,6.,7.],[7.,4.,9.,10.],[7.,4.,9.,37.]))
b=np.array([5.,9.,7.,8.])
GaussianElimination(mat,b)
print(la.solve(mat,b))
j=UTsol(GaussianElimination(mat,b)[0],GaussianElimination(mat,b)[1])
j

[-1.23148148  1.5         1.02777778  0.03703704]


array([-1.23148148,  1.5       ,  1.02777778,  0.03703704])

In [5]:
def ludec(mat_t):
    new_T=np.copy(mat_t)
    UT=new_T.copy()
    LT=np.identity(new_T.shape[0])
    for j in range(len(b)-1):
        coefficient=0
        for i in range(j+1,len(b)):
            coefficient=UT[i][j]/UT[j][j]
            UT[i]-=coefficient*UT[j]
            LT[i][j]=coefficient
    return [UT,LT]
matrix=np.array(([1.,2.,3.,4.],[15.,14.,13.,12.],[9.,6.,5.,4.],[9.,4.,5.,.2]))
ludec(matrix)

[array([[  1. ,   2. ,   3. ,   4. ],
        [  0. , -16. , -32. , -48. ],
        [  0. ,   0. ,   2. ,   4. ],
        [  0. ,   0. ,   0. ,  -5.8]]),
 array([[ 1.   ,  0.   ,  0.   ,  0.   ],
        [15.   ,  1.   ,  0.   ,  0.   ],
        [ 9.   ,  0.75 ,  1.   ,  0.   ],
        [ 9.   ,  0.875,  3.   ,  1.   ]])]

In [10]:
def GauElim(mat_T,b):
    new_T=mat_T.copy()
    bnew=np.copy(b)
    for j in range(len(b)-1):
        
        k = np.argmax(np.abs(new_T[j:,j])) + j
        if k != j:
            new_T[j,:], new_T[k,:] = new_T[k,:], new_T[j,:].copy()
            bnew[j], bnew[k] = bnew[k], bnew[j]
        for i in range(j+1,len(b)):
            coefficient=new_T[i][j]/new_T[j][j]
            new_T[i]-=coefficient*new_T[j]
            bnew[i]-=coefficient*bnew[j]
    return [new_T,bnew]
mat=np.array(([1.,2.,3.,4.],[15.,30.,13.,12.],[9.,6.,5.,4.],[9.,4.,5.,.2]))

In [11]:
GauElim(mat,b)

[array([[ 15.        ,  30.        ,  13.        ,  12.        ],
        [  0.        , -14.        ,  -2.8       ,  -7.        ],
        [  0.        ,   0.        ,   2.13333333,   3.2       ],
        [  0.        ,   0.        ,   0.        ,   3.4       ]]),
 array([9.        , 2.6       , 4.4       , 0.19642857])]

In [16]:
GaussianElimination(mat,b)

C:\Users\danie\AppData\Local\Temp\ipykernel_15900\3930226113.py:7: RuntimeWarning: divide by zero encountered in double_scalars
  coefficient=new_T[i][j]/new_T[j][j]
C:\Users\danie\AppData\Local\Temp\ipykernel_15900\3930226113.py:8: RuntimeWarning: invalid value encountered in multiply
  new_T[i]-=coefficient*new_T[j]
C:\Users\danie\AppData\Local\Temp\ipykernel_15900\3930226113.py:7: RuntimeWarning: invalid value encountered in double_scalars
  coefficient=new_T[i][j]/new_T[j][j]


[array([[  1.,   2.,   3.,   4.],
        [  0.,   0., -32., -48.],
        [ nan,  nan, -inf, -inf],
        [ nan,  nan,  nan,  nan]]),
 array([   8., -113.,  -inf,   nan])]

In [18]:
def gauelim_pivot(inA,inbs):
    A = np.copy(inA)
    bs = np.copy(inbs)
    n = bs.size
    for j in range(n-1):
        k = np.argmax(np.abs(A[j:,j])) + j
        if k != j:
            A[j,:], A[k,:] = A[k,:], A[j,:].copy()
            bs[j], bs[k] = bs[k], bs[j]
        for i in range(j+1,n):
            coeff = A[i,j]/A[j,j]
            A[i,j:] -= coeff*A[j,j:]
            bs[i] -= coeff*bs[j]
    return A
gauelim_pivot(mat,b)

array([[ 15.        ,  30.        ,  13.        ,  12.        ],
       [  0.        , -14.        ,  -2.8       ,  -7.        ],
       [  0.        ,   0.        ,   2.13333333,   3.2       ],
       [  0.        ,   0.        ,   0.        ,   3.4       ]])

Problem 